In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

In [ ]:
# p=sent_tokenize(h)

In [2]:
from ddgs import DDGS                                                                  # Imports the DDGS class from the ddgs package.
from collections import defaultdict                                                    # Imports defaultdict from Python collections
import urllib.request                                                                  # Imports tools to open URLs and download webpage content.
from bs4 import BeautifulSoup                                                          # Imports BeautifulSoup, used for parsing HTML webpages                                                       


movie=input("Enter movie name: ")                                                       # Asks the user to enter a movie name.
t=[]                                                                                    # Creates an empty list named t
with DDGS() as ddgs:                                                                    # Creates a DuckDuckGo search object
    results = ddgs.text(movie+ "user review", max_results=5)                              # Searches DuckDuckGo for:

    for r in results:                                                                    #  Loops through each search result one by one. ,  Each r is usually a dictionary like:
        print(r['href'])                                                                #  Print URL
        s=r['href']                                                                     #  Saves the URL into variable s.
        t.append(s)                                                                     #  Adds the URL into list t. 
        print(s)

Enter movie name:  The Ugly

https://en.wikipedia.org/wiki/Ugly_(film)
https://en.wikipedia.org/wiki/Ugly_(film)
https://www.rottentomatoes.com/m/the_ugly_2024
https://www.rottentomatoes.com/m/the_ugly_2024
https://www.screendaily.com/reviews/the-ugly-review-a-murder-mystery-links-past-and-present-in-yeon-sang-hos-calibrated-thriller/5208635.article
https://www.screendaily.com/reviews/the-ugly-review-a-murder-mystery-links-past-and-present-in-yeon-sang-hos-calibrated-thriller/5208635.article
https://www.quora.com/What-is-your-review-of-Ugly-2014-movie
https://www.quora.com/What-is-your-review-of-Ugly-2014-movie
https://www.facebook.com/groups/cyrussarki/posts/1979531099116451/
https://www.facebook.com/groups/cyrussarki/posts/1979531099116451/

In [3]:

import re                                                                                # re = Regular Expressions module.
h=[]                                                                                     # This list stores all extracted sentences.
for i in t:                                                                              # Loop visits each URL one by one.
    try:                                                                                 # Try Block
        response = urllib.request.urlopen(i)                                             # Connects to webpage URL.
        html = response.read()                                                           # Downloads webpage HTML.
        soup = BeautifulSoup(html)                                                       # BeautifulSoup converts raw HTML into a searchable structure.
        
        text = soup.get_text()                                                           # Removes HTML tags and keeps plain text.

        sentences = re.split(r' *[\.\?!][\'"\)\]]* *', text)                             # Split Text into Sentences
        for s in sentences:                                                              # Visits each sentence one by one.
            h.append(s)                                                                  # Adds sentence to list h

    except Exception as e:                                                               # Exception Handling
        print(e)

HTTP Error 403: Forbidden
HTTP Error 405: Not Allowed
HTTP Error 403: Forbidden

In [4]:
h

["\n\n\n\n\n\n\n\n\n\n\nThe Ugly (2024) | Rotten Tomatoes\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSigned in\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSkip to Main Content\n\n\n\n\n\n\n                                DOWNLOAD THE APP\n                            \n\n                                CONTINUE IN BROWSER\n                            \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSubmit search\n\n\n\n\n        Cancel\n      \n\n\n\n\n\n\n\n        About Rotten Tomatoes®\n      \n\n\n\n        Critics\n      \n\n\n\n\n\n            Login/signup\n          \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          \xa0Wants to See\n        \n\n\n\n          \xa0Reviews\n        \nProfile\nAccount\nLog Out\n\n\n\n\n\n\n\n\n\n        Movies\n      \n\n\nMovies in theaters\n\n\nOpening This Week\n\n\nTop Box Office\n\n\nComing Soon to Theaters\n\n\nCertified Fresh Movies\n\n\n\n\nMovies at Home\n\n\nFandango at Home\n\n\nNetflix\n\n\nApple TV\n\n\nPrime Video\n\n\nMost Popular Streaming movies\n\n\nCertified Fresh movies\n\n\nBrowse all\n\n\n\n\nMore\n\n\nWhat to WatchNew\n\n\n\n\nCertified fresh picks\n\n\n\n\n\n\n\n\n95%\n\nObsession\nLink to Obsession\n\n\n\n\n\n\n\n\n\n\n\n98%\n\nIs God Is\nLink to Is God Is\n\n\n\n\n\n\n\n\n\n\n\n95%\n\nTuner\nLink to Tuner\n\n\n\n\n\n\n\n\n\n\n        Tv shows\n      \n\n\n\n              New TV Tonight\n            \n\n\n\n\n\n91%\n\n\n        \n            Spider-Noir: Season 1\n        \n    \n\n\n\n\n\n\n30%\n\n\n        \n            Summerwater: Season 1\n        \n    \n\n\n\n\n\n\n100%\n\n\n        \n            Rick and Morty: Season 9\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            Star City: Season 1\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            The Four Seasons: Season 2\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            A Good Girl's Guide to Murder: Season 2\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            Deli Boys: Season 2\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            World War II With Tom Hanks: Season 1\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            Criminal Minds: Evolution: Season 19\n        \n    \n\n\n\n\n\n\n--\n\n\n        \n            Calabasas Confidential: Season 1\n        \n    \n\n\n\n\n                View All\n            \n\n\n\n              Most Popular TV on RT\n            \n\n\n\n\n\n95%\n\n\n        \n            The Boroughs: Season 1\n        \n    \n\n\n\n\n\n\n92%\n\n\n        \n            The Boys: Season 5\n        \n    \n\n\n\n\n\n\n92%\n\n\n        \n            Maximum Pleasure Guaranteed: Season 1\n        \n    \n\n\n\n\n\n\n91%\n\n\n        \n            Spider-Noir: Season 1\n        \n    \n\n\n\n\n\n\n93%\n\n\n        \n            Off Campus: Season 1\n        \n    \n\n\n\n\n\n\n97%\n\n\n        \n            Widow's Bay: Season 1\n        \n    \n\n\n\n\n\n\n96%\n\n\n        \n            Legends: Season 1\n        \n    \n\n\n\n\n\n\n92%\n\n\n        \n            Nemesis: Season 1\n        \n    \n\n\n\n\n\n\n100%\n\n\n        \n            Rivals: Season 2\n        \n    \n\n\n\n\n                View All\n            \n\n\nMore\n\n\n\n                What to WatchNew\n\n\n\n\nBest TV Shows\n\n\n\n\nMost Popular TV\n\n\n\n\nFandango at Home\n\n\n\n\nParamount+\n\n\n\n\nNetflix\n\n\n\n\nPrime Video\n\n\n\n\nApple TV\n\n\n\n\n\n\n              Certified fresh pick\n            \n\n\n\n\n\n\n\n\n100%\n\nRivals: Season 2\nLink to Rivals: Season 2\n\n\n\n\n\n\n\n\n\n\n          RT App\n          \nNew\n\n\n\n\n\n        News\n      \n\n\nColumns\n\n\n\n                All-Time Lists\n              \n\n\n\n                Binge Guide\n              \n\n\n\n                Comics on TV\n              \n\n\n\n                Countdown\n              \n\n\n\n                Five Favorite Films\n              \n\n\n\n                Video Interviews\n              \n\n\nWeekend Box Office\n            \n\n\n\n                Weekly Ketchup\n              \n\n\n\n                What to Watch\n              \n\n\n\n\nGuides\n\n\n\n\n\n\nEvery Cannes Palme d’Or Winner Since 1955, Ranked by Tomatometer\nLink to Every Cannes Palme d’Or Winner Since 1955, Ranked by Tomatometer\n\n\n\n\n\n\n\n\n\nCannes 2026 Movies Ranked by Tomatometer\nLink to Cannes 2026 Movies Ranked by Tomatometer\n\n\n\n\n\n\n              View All\n            \n\n\nHubs\n\n\n\n\n\n\nAwards Tour\nLink to Awards Tour\n\n\n\n\n\n\n\n\n\nWhat to Watch: In Theaters and On Streaming\nLink to What to Watch: In Theaters and On Streaming\n\n\n\n\n\n\n              View All\n            \n\n\nRT News\n\n\n\n\n\n\n2026 Crunchyroll Anime Awards: Full List of Winners\nLink to 2026 Crunchyroll Anime Awards: Full List of Winners\n\n\n\n\n\n\n\n\n\nSpider-Noir First Reviews: A Bold, Beautiful Experiment Led by a Gonzo Nic Cage Performance\nLink to Spider-Noir First Reviews: A Bold, Beautiful Experiment Led by a Gonzo Nic Cage Performance\n\n\n\n\n\n\n              View All\n            \n\n\n\n\n\n        Showtimes\n      \n\n\n\n\n\n\n\n\n\n\nTrending on RT\n Seen on the Screen \n Rotten Tomatoes App  \n Cannes 2026 \n Women in Focus \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n The Ugly  \n\n\nPlay trailer\n1:30\n\n\nThe Ugly\n\n2025\n1h 42m\nMystery & Thriller\n\n Play Trailer\n    \n\nWatchlist\n\n\n\n\n\nWatchlist\n\n\n\n\nTomatometer\n\n\n\nPopcornmeter\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n55%\nTomatometer\n\n            31 Reviews\n        \n\n\n\n\nPopcornmeter\n\n            Fewer than 50 Ratings\n        \n\n\n\n                    From director Yeon Sang-ho (Train to Busan, Peninsula) comes a story of generational grief and guilt",
 "One day while overseeing a documentary crew filming his blind father at work, Im Dong-hwan gets a phone call that his missing mother's remains have been found after forty years",
 "Determined to find the truth of her disappearance, Dong-hwan embarks on a twisted odyssey through his family's traumatic past, uncovering dark secrets along the way",
 '\n                \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nWhere to Watch\n\n\nReviews\n\n\nCast & Crew\n\n\nVideos\n\n\nPhotos\n\n\nMedia Info\n\n\n\n\n\n\n\n\n\nWhere to Watch\n\n\n\n        The Ugly\n      \n\n\n\n\n\n\n\n\n\n\nFandango at Home\n\n\n\nRent The Ugly on Fandango at Home, or buy it on Fandango at Home',
 '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCritics Reviews\n\n\n      View More\n    \n\n\n\n\n\n\n\n\n\n\n\n            Nick Schager\n          \n\n            The Daily Beast\n          \nSep 22\n\n\n\n\nIt builds to revelations that speak emphatically to social shallowness, pressures and prejudices—even if, in the end, its bombshells resonate as less surprising than inevitable',
 "\n\n              Go to Full Review\n            \n\n\n\n\n\n\n\n            Kristy Puchko\n          \n\n            Mashable\n          \nSep 16\n\n\n\n\nThe Ugly is a stirring thriller, bolstered by dark twists, and paid off with a final scene that plays like a monkey's paw curling",
 '\n\n              Go to Full Review\n            \n\n\n\n\n\n\n\n            Brian Tallerico\n          \n\n            RogerEbert',
 'com\n          \nSep 10\n\n\n1',
 '5/4\n\nThe film is a dour, depressing drama, a movie that gets so lost in its lethargic structure that it feels like a chore',
 '\n\n              Go to Full Review\n            \n\n\n\n\n\n\n\n            George and Josh Bate\n          \n\n            ScreenAnarchy\n          \nMar 3\n\n\n3/5\n\nYeon Sang-ho crafts an intimate, emotionally charged, and eventually gut-wrenching film',
 '\n\n              Go to Full Review\n            \n\n\n\n\n\n\n\n            Angelo Muredda\n          \n\n            Film Freak Central\n          \nOct 17\n\n\n1',
 '5/4\n\nThe Ugly is thrown into a full-blown panic attack by the aesthetic challenge posed by something as simple as depicting its disabled characters moving through the world',
 '\n\n              Go to Full Review\n            \n\n\n\n\n\n\n\n            Brogan Luke Bouwhuis\n          \n\n            InBetweenDrafts\n          \nOct 6\n\n\n7/10\n\nYeon’s direction, Pyo’s cinematography, and Park’s dual performance are more than enough to compensate for the film’s shortcomings',
 '\n\n              Go to Full Review\n            \n\n\n\n\n          Read all reviews\n        \n\n\n\n\n\n\n\n\n\nAudience Reviews\n\n\n      View More\n    \n\n\n\n\n\n\n\n\n\n\n\n\n            B P\n          \n@Bradster69\n\n\n\nMay 2\n\n\n‘Train to Busan’ Director’s Latest Investigates a 40 Year Old Murder\n\n\n              See more\n            \n\n\n\n\n\n\n            elvin O\n          \n@ellvin\n\n\n\nApr 3\n\n\nPark Jeong-min profesyonel oyunculuğu için tebrik ederim',
 '\n\n\n              See more\n            \n\n\n\n\n\n\n            Sarvika S\n          \n@88radley\n\n\n\nFeb 5\n\n\n The movie is an interesting watch and acts as a reflection of society’s notions of beauty and character, and how often our perception of another human being is moulded entirely by outer appearances',
 'It explores a fresh theme, not widely covered in cinema, though the best thing about the film is the performances of the cast, especially Park Jeong Min',
 '\n\n\n              See more\n            \n\n\n\n\n\n\n            Musheeza S\n          \n@Musheeza_s\n\n\n\nJan 24\n\n\nThe beginning was good',
 'But there were a few things which seemed illogical',
 'First, that if a blind man murdered someone, how can he go to the mountains and just throw the body like no one on his way can see and report him',
 'Second, if he is blind what does he have to do with her face',
 'I understand the part where he tells he was being laughed at for everything, but the woman was the one who married him despite being blind, she was kind to him even before he asked her to get married',
 'He should have been thankful to her',
 'The woman was not shown in the whole movie and at the end it was just 1 picture',
 'That was the only suspense in this movie',
 'It could have been better but the writer left a few holes in the script',
 '\n\n\n              See more\n            \n\n\n\n\n\n\n            Alessio C\n          \n@alessiocherry\n\n\n\nOct 4\n\n\n"The Ugly" surprised me',
 'The premise was nothing special, but damn - the director managed to build real tension out of thin air',
 'The suspense was thick, acting on point, and even the usual Korean overdrama stayed on the right side of believable',
 'It did drag a bit in the final act, though, when the mystery was already solved - and showing the mother’s face at the end kinda ruined the beautiful ambiguity they’d built',
 'Still, a strong, moody thriller that proves atmosphere can beat plot any day',
 '\n7/10\n\n\n              See more\n            \n\n\n\n\n\n\n            Johnny A\n          \n@JonnyTo72\n\n\n\nSep 26\n\n\nThis murder mystery was well worth the watch',
 "Enjoyed the story and it's tense dive into the ugly truth the community in the film tried to hide and ignore",
 '\n\n\n              See more\n            \n\n\n\n          Read all reviews\n        \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n      The Ugly\n    \n\nMy Rating\n\n\n\n\n\n\n\n\n\nRead More\nRead Less\n\n WRITE A REVIEW \n EDIT REVIEW \n POST RATING \n\n\n\n\n\n\n\n\n\n\n\nCast & Crew\n\n\n      View All\n    \n\n\n\n\n\n\nYeon Sang-ho\nDirector\n\n\n\n\n\n\n\nPark Jeong-min\nActor\n\n\n\n\n\n\n\nKwon Hae-hyo\nActor\n\n\n\n\n\n\n\nShin Hyun-been\nActor\n\n\n\n\n\n\n\nIm Sung-jae\nActor\n\n\n\n\n\n\n\nHan Ji-hyeon\nActor\n\n\n\n\n\n\n\n\n\n\n\n\nVideos\n\n\n        View All\n      \n\n\n\n        The Ugly\n      \n\n\n\n\n\n\nThe Ugly: Trailer 1\n\n\nThe Ugly: Trailer 1\n\n\n            1:30\n          \n\n\n\n\nThe Ugly: Teaser Trailer\n\n\nThe Ugly: Teaser Trailer\n\n\n            1:07\n          \n\n\n\n          View more videos\n        \n\n\n\n\n\n\n\n\n\n\nPhotos\n\n\n        View All\n      \n\n\n\n        The Ugly\n      \n\n\n\n\n\n\n\n\nThe Ugly (2025)\n\n\n\n\n\n\n\nThe Ugly (2025)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n          View more photos\n        \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n        Movie Info\n      \n\n\n\n\nSynopsis\nFrom director Yeon Sang-ho (Train to Busan, Peninsula) comes a story of generational grief and guilt',
 "One day while overseeing a documentary crew filming his blind father at work, Im Dong-hwan gets a phone call that his missing mother's remains have been found after forty years",
 "Determined to find the truth of her disappearance, Dong-hwan embarks on a twisted odyssey through his family's traumatic past, uncovering dark secrets along the way",
 '\n\n\n\n\nDirector\n\n\nYeon Sang-ho\n\n\n\n\nScreenwriter\n\n\nYeon Sang-ho\n\n\n\n\nDistributor\n\n\nWell Go USA Entertainment\n\n\n\n\nProduction Co\n\n\nWow Point\n\n\n\n\nGenre\n\n\nMystery & Thriller\n\n\n\n\nOriginal Language\n\n\nKorean\n\n\n\n\nRelease Date (Theaters)\n\n\nSep 26, 2025, Limited\n\n\n\n\nBox Office (Gross USA)\n\n\n$53',
 '6K\n\n\n\n\nRuntime\n\n\n1h 42m\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCommunity Watch\n\n        "" is under\n        Community Watch',
 '\n        Please write a review for your rating to count toward the Popcornmeter',
 '\n    \nWrite a review\n\n\n\n\nThanks for your submission',
 '\n\n        Your review is awaiting approval',
 'Once accepted, your review will get its big debut\n        in the Popcornmeter',
 'Visit\n        FAQ\n        to learn more about Community Watch',
 '\n    \nGot it\n\n\n\n\n- -\n\n\n\n\n\n\n\n\n            \u2002 Tap to Unmute\n        \n\n\n\nClose video\n\n\nSee Details\n\n\nSee Details\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nHelp\n\n\nAbout Rotten Tomatoes\n\n\n\n\n\n\n\n\nCritic Submission\n\n\nLicensing\n\n\nAdvertise With Us\n\n\nCareers\n\n\n\n\n\n\u2002Join the Newsletter\n            \nGet the freshest reviews, news, and more delivered right to your inbox',
 '\n\n                Join The Newsletter\n            \n\n                Join The Newsletter\n            \n\n\nFollow Us\n\n\n\n\n\n\n\n\n\nCopyright © Fandango',
 'All rights reserved',
 '\n\n\n\n                    Join The Newsletter\n                \n\nJoin The Newsletter\n\n\nAd Choices\n\n\n\n                        Privacy Policy\n                    \n\n\n\n\nCookie Settings\n\n\n\nCA Notice\n\n\nTerms and Policies\n\n\nAccessibility\n\n\n\n\n\n\n\n\n\nV3',
 '1\n\n\nAd Choices\n\n\n\n                    Privacy Policy\n                \n\n\n\n\nCookie Settings\n\n\n\nCA Notice\n\n\nTerms and Policies\n\n\nAccessibility\n\n\n\n            Copyright © Fandango',
 'A\n            \n                Versant Media\n             company',
 'All rights reserved',
 '\n        \n\n\n\n\nbeta\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n',
 '\n\n\n\n\n\n\n\n\n\n\n\n\nGrand Ole Times | The Good, The Bad And The Ugly, In India 🎭 Circa 1966\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n']

In [5]:
import pandas as pd
df=pd.DataFrame(h, columns=['Review'])
df

                                               Review
0   \n\n\n\n\n\n\n\n\n\n\nThe Ugly (2024) | Rotten...
1   One day while overseeing a documentary crew fi...
2   Determined to find the truth of her disappeara...
3   \n                \n\n\n\n\n\n\n\n\n\n\n\n\n\n...
4   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCritics Reviews\...
5   \n\n              Go to Full Review\n         ...
6   \n\n              Go to Full Review\n         ...
7                      com\n          \nSep 10\n\n\n1
8   5/4\n\nThe film is a dour, depressing drama, a...
9   \n\n              Go to Full Review\n         ...
10  \n\n              Go to Full Review\n         ...
11  5/4\n\nThe Ugly is thrown into a full-blown pa...
12  \n\n              Go to Full Review\n         ...
13  \n\n              Go to Full Review\n         ...
14  \n\n\n              See more\n            \n\n...
15  It explores a fresh theme, not widely covered ...
16  \n\n\n              See more\n            \n\n...
17  But there were a few things which seemed illog...
18  First, that if a blind man murdered someone, h...
19  Second, if he is blind what does he have to do...
20  I understand the part where he tells he was be...
21                He should have been thankful to her
22  The woman was not shown in the whole movie and...
23           That was the only suspense in this movie
24  It could have been better but the writer left ...
25  \n\n\n              See more\n            \n\n...
26  The premise was nothing special, but damn - th...
27  The suspense was thick, acting on point, and e...
28  It did drag a bit in the final act, though, wh...
29  Still, a strong, moody thriller that proves at...
30  \n7/10\n\n\n              See more\n          ...
31  Enjoyed the story and it's tense dive into the...
32  \n\n\n              See more\n            \n\n...
33  One day while overseeing a documentary crew fi...
34  Determined to find the truth of her disappeara...
35  \n\n\n\n\nDirector\n\n\nYeon Sang-ho\n\n\n\n\n...
36  6K\n\n\n\n\nRuntime\n\n\n1h 42m\n\n\n\n\n\n\n\...
37  \n        Please write a review for your ratin...
38  \n    \nWrite a review\n\n\n\n\nThanks for you...
39       \n\n        Your review is awaiting approval
40  Once accepted, your review will get its big de...
41  Visit\n        FAQ\n        to learn more abou...
42  \n    \nGot it\n\n\n\n\n- -\n\n\n\n\n\n\n\n\n ...
43  \n\n                Join The Newsletter\n     ...
44                                All rights reserved
45  \n\n\n\n                    Join The Newslette...
46  1\n\n\nAd Choices\n\n\n\n                    P...
47  A\n            \n                Versant Media...
48                                All rights reserved
49  \n        \n\n\n\n\nbeta\n\n\n\n\n\n\n\n\n\n\n...
50  \n\n\n\n\n\n\n\n\n\n\n\n\nGrand Ole Times | Th...

In [6]:
def cleanTxt(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text)                                                    # Remove mentions
    text = re.sub(r'#', '', text)                                                                # Remove hashtag symbol
    text = re.sub(r'RT[\s]+', '', text)                                                          # Remove RT
    text = re.sub(r'https?:\/\/S+', '', text)                                                    # Remove URLs
    text = re.sub(r'0', '', text)                                                                # # Remove numbers
    text = re.sub(r'[0-9]', '', text)
    text = re.sub(r'%', '', text)                                                                # Remove %
    text = re.sub(r'\n', '', text)                                                               # Remove newlines
    return text

In [7]:
df['Review'] = df['Review'].apply(cleanTxt)
df

                                               Review
0   The Ugly () | Rotten TomatoesSigned inSkip to ...
1   One day while overseeing a documentary crew fi...
2   Determined to find the truth of her disappeara...
3                   Where to WatchReviewsCast & Cr...
4   Critics Reviews      View More                ...
5                 Go to Full Review               ...
6                 Go to Full Review               ...
7                                   com          Sep
8   /The film is a dour, depressing drama, a movie...
9                 Go to Full Review               ...
10                Go to Full Review               ...
11  /The Ugly is thrown into a full-blown panic at...
12                Go to Full Review               ...
13                Go to Full Review               ...
14                See more                        ...
15  It explores a fresh theme, not widely covered ...
16                See more                        ...
17  But there were a few things which seemed illog...
18  First, that if a blind man murdered someone, h...
19  Second, if he is blind what does he have to do...
20  I understand the part where he tells he was be...
21                He should have been thankful to her
22  The woman was not shown in the whole movie and...
23           That was the only suspense in this movie
24  It could have been better but the writer left ...
25                See more                        ...
26  The premise was nothing special, but damn - th...
27  The suspense was thick, acting on point, and e...
28  It did drag a bit in the final act, though, wh...
29  Still, a strong, moody thriller that proves at...
30  /              See more                       ...
31  Enjoyed the story and it's tense dive into the...
32                See more                      Re...
33  One day while overseeing a documentary crew fi...
34  Determined to find the truth of her disappeara...
35  DirectorYeon Sang-hoScreenwriterYeon Sang-hoDi...
36  KRuntimeh mCommunity Watch        "" is under ...
37          Please write a review for your rating ...
38           Write a reviewThanks for your submission
39                   Your review is awaiting approval
40  Once accepted, your review will get its big de...
41  Visit        FAQ        to learn more about Co...
42      Got it- -              Tap to Unmute      ...
43                  Join The Newsletter           ...
44                                All rights reserved
45                      Join The Newsletter       ...
46  Ad Choices                    Privacy Policy  ...
47  A                            Versant Media    ...
48                                All rights reserved
49                                               beta
50  Grand Ole Times | The Good, The Bad And The Ug...

In [8]:
from afinn import Afinn
positive = []
negative = []
neutral = []

afinn = Afinn()

for review in df['Review']:
    if afinn.score(review) > 0:
        positive.append(review)
    elif afinn.score(review) <0:
        negative.append(review)
    elif afinn.score(review)==0:
        neutral.append(review)


print("Postive Reviews :", positive)
print(r'\t\n')
print("Negative Reviews :", negative)
print(r'\t\n')
print("neutral Reviews :", neutral)
print(r'\t\n')
total_reviews = len(df['Review'])
print("Total number of reviews :" ,total_reviews )
print("number of positive reviews :",  len(positive))
print("number of negative reviews :",  len(negative ))
print("number of neutural reviews :",  len(neutral))

Postive Reviews : ["The Ugly () | Rotten TomatoesSigned inSkip to Main Content                                DOWNLOAD THE APP                                                            CONTINUE IN BROWSER                            Submit search        Cancel              About Rotten Tomatoes®              Critics                  Login/signup                    \xa0Wants to See                  \xa0Reviews        ProfileAccountLog Out        Movies      Movies in theatersOpening This WeekTop Box OfficeComing Soon to TheatersCertified Fresh MoviesMovies at HomeFandango at HomeNetflixApple TVPrime VideoMost Popular Streaming moviesCertified Fresh moviesBrowse allMoreWhat to WatchNewCertified fresh picksObsessionLink to ObsessionIs God IsLink to Is God IsTunerLink to Tuner        Tv shows                    New TV Tonight                                Spider-Noir: Season                                 Summerwater: Season                                 Rick and Morty: Season             --                    Star City: Season             --                    The Four Seasons: Season             --                    A Good Girl's Guide to Murder: Season             --                    Deli Boys: Season             --                    World War II With Tom Hanks: Season             --                    Criminal Minds: Evolution: Season             --                    Calabasas Confidential: Season                             View All                          Most Popular TV on                     The Boroughs: Season                                 The Boys: Season                                 Maximum Pleasure Guaranteed: Season                                 Spider-Noir: Season                                 Off Campus: Season                                 Widow's Bay: Season                                 Legends: Season                                 Nemesis: Season                                 Rivals: Season                             View All            More                What to WatchNewBest TV ShowsMost Popular TVFandango at HomeParamount+NetflixPrime VideoApple TV              Certified fresh pick            Rivals: Season Link to Rivals: Season           App          New        News      Columns                All-Time Lists                              Binge Guide                              Comics on TV                              Countdown                              Five Favorite Films                              Video Interviews              Weekend Box Office                            Weekly Ketchup                              What to Watch              GuidesEvery Cannes Palme d’Or Winner Since , Ranked by TomatometerLink to Every Cannes Palme d’Or Winner Since , Ranked by TomatometerCannes  Movies Ranked by TomatometerLink to Cannes  Movies Ranked by Tomatometer              View All            HubsAwards TourLink to Awards TourWhat to Watch: In Theaters and On StreamingLink to What to Watch: In Theaters and On Streaming              View All            News Crunchyroll Anime Awards: Full List of WinnersLink to  Crunchyroll Anime Awards: Full List of WinnersSpider-Noir First Reviews: A Bold, Beautiful Experiment Led by a Gonzo Nic Cage PerformanceLink to Spider-Noir First Reviews: A Bold, Beautiful Experiment Led by a Gonzo Nic Cage Performance              View All                    Showtimes      Trending on Seen on the Screen  Rotten Tomatoes App   Cannes   Women in Focus  The Ugly  Play trailer:The Uglyh mMystery & Thriller Play Trailer    WatchlistWatchlistTomatometerPopcornmeterTomatometer             Reviews        Popcornmeter            Fewer than  Ratings                            From director Yeon Sang-ho (Train to Busan, Peninsula) comes a story of generational grief and guilt", '              See more                        Sarvika S          Feb  The movie is an interesting watch and acts as a reflection of society’s notions of beauty and character, and how often our perception of another human being is moulded entirely by outer appearances', 'It explores a fresh theme, not widely covered in cinema, though the best thing about the film is the performances of the cast, especially Park Jeong Min', '              See more                        Musheeza S          _sJan The beginning was good', 'I understand the part where he tells he was being laughed at for everything, but the woman was the one who married him despite being blind, she was kind to him even before he asked her to get married', 'He should have been thankful to her', 'It could have been better but the writer left a few holes in the script', 'It did drag a bit in the final act, though, when the mystery was already solved - and showing the mother’s face at the end kinda ruined the beautiful ambiguity they’d built', 'Still, a strong, moody thriller that proves atmosphere can beat plot any day', '        Please write a review for your rating to count toward the Popcornmeter', '        Your review is awaiting approval', 'Once accepted, your review will get its big debut        in the Popcornmeter', '                Join The Newsletter                            Join The Newsletter            Follow UsCopyright © Fandango', '                    Join The Newsletter                Join The NewsletterAd Choices                        Privacy Policy                    Cookie SettingsCA NoticeTerms and PoliciesAccessibilityV']
\t\n
Negative Reviews : ["One day while overseeing a documentary crew filming his blind father at work, Im Dong-hwan gets a phone call that his missing mother's remains have been found after forty years", "Determined to find the truth of her disappearance, Dong-hwan embarks on a twisted odyssey through his family's traumatic past, uncovering dark secrets along the way", '                Where to WatchReviewsCast & CrewVideosPhotosMedia InfoWhere to Watch        The Ugly      Fandango at HomeRent The Ugly on Fandango at Home, or buy it on Fandango at Home', 'Critics Reviews      View More                Nick Schager                      The Daily Beast          Sep It builds to revelations that speak emphatically to social shallowness, pressures and prejudices—even if, in the end, its bombshells resonate as less surprising than inevitable', "              Go to Full Review                        Kristy Puchko                      Mashable          Sep The Ugly is a stirring thriller, bolstered by dark twists, and paid off with a final scene that plays like a monkey's paw curling", '/The film is a dour, depressing drama, a movie that gets so lost in its lethargic structure that it feels like a chore', '              Go to Full Review                        George and Josh Bate                      ScreenAnarchy          Mar /Yeon Sang-ho crafts an intimate, emotionally charged, and eventually gut-wrenching film', '              Go to Full Review                        Angelo Muredda                      Film Freak Central          Oct ', '/The Ugly is thrown into a full-blown panic attack by the aesthetic challenge posed by something as simple as depicting its disabled characters moving through the world', '              Go to Full Review                      Read all reviews        Audience Reviews      View More                B P          May ‘Train to Busan’ Director’s Latest Investigates a  Year Old Murder              See more                        elvin O          Apr Park Jeong-min profesyonel oyunculuğu için tebrik ederim', 'But there were a few things which seemed illogical', 'Second, if he is blind what does he have to do with her face', '              See more                        Alessio C          Oct "The Ugly" surprised me', 'The premise was nothing special, but damn - the director managed to build real tension out of thin air', "Enjoyed the story and it's tense dive into the ugly truth the community in the film tried to hide and ignore", '              See more                      Read all reviews              The Ugly    My RatingRead MoreRead Less WRITE A REVIEW  EDIT REVIEW  POST RATING Cast & Crew      View All    Yeon Sang-hoDirectorPark Jeong-minActorKwon Hae-hyoActorShin Hyun-beenActorIm Sung-jaeActorHan Ji-hyeonActorVideos        View All              The Ugly      The Ugly: Trailer The Ugly: Trailer             :          The Ugly: Teaser TrailerThe Ugly: Teaser Trailer            :                    View more videos        Photos        View All              The Ugly      The Ugly ()The Ugly ()          View more photos                Movie Info      SynopsisFrom director Yeon Sang-ho (Train to Busan, Peninsula) comes a story of generational grief and guilt', "One day while overseeing a documentary crew filming his blind father at work, Im Dong-hwan gets a phone call that his missing mother's remains have been found after forty years", "Determined to find the truth of her disappearance, Dong-hwan embarks on a twisted odyssey through his family's traumatic past, uncovering dark secrets along the way", 'DirectorYeon Sang-hoScreenwriterYeon Sang-hoDistributorWell Go USA EntertainmentProduction CoWow PointGenreMystery & ThrillerOriginal LanguageKoreanRelease Date (Theaters)Sep , , LimitedBox Office (Gross USA)$', '    Got it- -            \u2002 Tap to Unmute        Close videoSee DetailsSee DetailsHelpAbout Rotten TomatoesCritic SubmissionLicensingAdvertise With UsCareers\u2002Join the Newsletter            Get the freshest reviews, news, and more delivered right to your inbox']
\t\n
neutral Reviews : ['              Go to Full Review                        Brian Tallerico                      RogerEbert', 'com          Sep ', '              Go to Full Review                        Brogan Luke Bouwhuis                      InBetweenDrafts          Oct /Yeon’s direction, Pyo’s cinematography, and Park’s dual performance are more than enough to compensate for the film’s shortcomings', 'First, that if a blind man murdered someone, how can he go to the mountains and just throw the body like no one on his way can see and report him', 'The woman was not shown in the whole movie and at the end it was just  picture', 'That was the only suspense in this movie', 'The suspense was thick, acting on point, and even the usual Korean overdrama stayed on the right side of believable', '/              See more                        Johnny A          Sep This murder mystery was well worth the watch', 'KRuntimeh mCommunity Watch        "" is under        Community Watch', '    Write a reviewThanks for your submission', 'Visit        FAQ        to learn more about Community Watch', 'All rights reserved', 'Ad Choices                    Privacy Policy                Cookie SettingsCA NoticeTerms and PoliciesAccessibility            Copyright © Fandango', 'A                            Versant Media             company', 'All rights reserved', '        beta', 'Grand Ole Times | The Good, The Bad And The Ugly, In India 🎭 Circa ']
\t\n
Total number of reviews : 51
number of positive reviews : 14
number of negative reviews : 20
number of neutural reviews : 17